name: (CI) Tests
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - run: pnpm run generate
      - run: pnpm exec -- prettier --check .
      - run: pnpm exec -- eslint .
      - run: pnpm exec -- tsc --noEmit
      - run: pnpm run test
